### ISSUE TITLE
安装运行后 只要打开网址就报错为什么呀 报错信息如下

### ISSUE THREAD

**Issue by mayunhai** [PanJiaChen/vue-element-admin-site#34]
(node:7656) UnhandledPromiseRejectionWarning: TypeError: res.getHeader is not a function
    at processRequest (D:\vue-element-admin-site-master\node_modules\webpack-dev-middleware\lib\middleware.js:82:18)
    at ready (D:\vue-element-admin-site-master\node_modules\webpack-dev-middleware\lib\util.js:51:12)
    at handleRequest (D:\vue-element-admin-site-master\node_modules\webpack-dev-middleware\lib\util.js:167:5)
    at Promise (D:\vue-element-admin-site-master\node_modules\webpack-dev-middleware\lib\middleware.js:44:7)
    at new Promise (<anonymous>)
    at middleware (D:\vue-element-admin-site-master\node_modules\webpack-dev-middleware\lib\middleware.js:43:12)
    at Promise.all.Promise (D:\vue-element-admin-site-master\node_modules\koa-webpack\index.js:43:7)
    at new Promise (<anonymous>)
    at D:\vue-element-admin-site-master\node_modules\koa-webpack\index.js:42:5
    at dispatch (D:\vue-element-admin-site-master\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at D:\vue-element-admin-site-master\node_modules\@shellscape\koa-static\legacy\index.js:58:19
    at Generator.throw (<anonymous>)
    at step (D:\vue-element-admin-site-master\node_modules\@shellscape\koa-static\legacy\index.js:6:221)
    at _throw (D:\vue-element-admin-site-master\node_modules\@shellscape\koa-static\legacy\index.js:6:455)
(node:7656) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7656) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

awesome-bookmarks 也是一样 想找个 vuepress的解决方案 0.0

**Comment by PanJiaChen** [comment]
https://github.com/vuejs/vuepress/issues/1417

和本项目无关吧。

**Comment by mayunhai** [comment]
已解决，确实和本项目无关，谢谢大神指点
